# Generated by Django 5.0 on 2024-01-20 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
        ('users', '0004_alter_follow_follower_alter_follow_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='messages',
            field=models.ManyToManyField(blank=True, to='chats.message'),
        ),
    ]
