# Generated by Django 5.0 on 2024-01-21 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_messages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='messages',
        ),
    ]
