# Generated by Django 5.0 on 2024-02-19 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_profile_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.CharField(blank=True, default='https://s3.timeweb.cloud/2d183873-povel-bucket/user-default.png', null=True),
        ),
    ]
