# Generated by Django 5.0 on 2024-01-13 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='release_year',
        ),
    ]
