# Generated by Django 5.0 on 2024-01-17 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_movie', to='movies.movie'),
        ),
    ]
