# Generated by Django 5.0 on 2024-02-25 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_alter_like_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
